name: Lua CI (5.1, 5.2, 5.3, 5.4)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test with Lua ${{ matrix.luaVersion }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # TODO: bring back luajit
        # luaVersion: [5.1, 5.2, 5.3, 5.4, luajit-2.1]
        luaVersion: [5.1, 5.2, 5.3, 5.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Run tests
        run: |
          find tests/ -name '*.lua' -exec lua {} --stop-on-fail \;