name: Lua CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test with Lua ${{ matrix.lua-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lua-version: [5.1, 5.2, 5.3, 5.4, luajit]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v8
        with:
          lua-version: ${{ matrix.lua-version }}

      - name: Run tests
        run: |
          find tests/ -name '*.lua' -exec lua {} \;